name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "frontend/**"

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: |
          cd frontend
          npm ci
          npm run build
          npm run test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - run: |
          cd frontend
          npm install
          npm run lint
